//
// Created by rodion on 07.11.22.
//

#ifndef PROXY_CONFIGURATION_H
#define PROXY_CONFIGURATION_H

#define PROXY_ADDR "127.0.0.1"
#define PROXY_PORT 8083

#define MAX_COUNT_THREAD 3

#define MAX_CLIENT 20
#define BUF_STEP_SIZE_RESPONSE 5000
#define BUF_STEP_SIZE_REQUEST 100
#define TIME_OUT_POLL -1

#define PERIOD_CASH_EVENT 30

#endif //PROXY_CONFIGURATION_H
